package:
  name: osg
  version: 3.5.5

source:
  fn: osg.tar.gz
  url: https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.5.5.tar.gz
  sha256: f44c96ade3a1d3c547f36504d75633bedbb9b8f6f42dac4fff75166db7d3aadf

  patches:

build:
  number: 0
  skip: true  # [win and not py35]

  track_features:
    - vc14  # [win and py35]

requirements:
  build:
    - cmake  # [unix]
    - ninja  # [win]
    - python  # [win]
    - toolchain  # [osx]
  run:
    - boost 1.61.*


test:

about:
  home: http://www.openscenegraph.org/
  license_family: LGPL
  license: OSGPL
  summary: this is Open Scene Graph
  description: The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application
               developers in fields such as visual simulation, games, virtual reality, scientific visualization
               and modelling. Written entirely in Standard C++ and OpenGL it runs on all Windows platforms, OSX,
               GNU/Linux, IRIX, Solaris, HP-Ux, AIX and FreeBSD operating systems. The OpenSceneGraph is now well
               established as the world leading scene graph technology, used widely in the vis-sim, space, scientific,
               oil-gas, games and virtual reality industries.
  doc_url: http://www.openscenegraph.org/
  dev_url: https://github.com/openscenegraph/OpenSceneGraph

extra:
  recipe-maintainers:
    - looooo
